# Generated by Django 4.1.6 on 2023-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
