# Generated by Django 4.1.6 on 2023-02-16 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={"verbose_name_plural": "work"},
        ),
    ]
