# Generated by Django 4.1.6 on 2023-02-11 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MedicalCareProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "exp",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="experience"
                    ),
                ),
                ("phlebotomy", models.BooleanField(default=False)),
                ("practice_nurse", models.BooleanField(default=False)),
                ("iv_skills", models.BooleanField(default=False)),
                ("tracheotomy", models.BooleanField(default=False)),
                ("peg_feeds", models.BooleanField(default=False)),
                ("administrating_injection", models.BooleanField(default=False)),
                ("vaccinations", models.BooleanField(default=False)),
                ("female_catheterisation", models.BooleanField(default=False)),
                ("male_catheterisation", models.BooleanField(default=False)),
                ("palliative_care", models.BooleanField(default=False)),
                ("itu", models.BooleanField(default=False)),
                ("a_e", models.BooleanField(default=False, verbose_name="A&E")),
                ("wound_care", models.BooleanField(default=False)),
                ("nurse_practitioner", models.BooleanField(default=False)),
                ("system_one_user", models.BooleanField(default=False)),
                ("smart_care_user", models.BooleanField(default=False)),
                (
                    "carer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(
                        related_name="qualification_list", to="med_care.qualification"
                    ),
                ),
            ],
        ),
    ]
