# Generated by Django 4.1.6 on 2023-02-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="exp",
            field=models.CharField(
                help_text="Number of years of experience",
                max_length=255,
                verbose_name="experience",
            ),
        ),
    ]
