# Generated by Django 4.1.6 on 2023-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0002_alter_medicalcareprofile_exp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="itu",
            field=models.BooleanField(default=False, verbose_name="ITU"),
        ),
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="iv_skills",
            field=models.BooleanField(default=False, verbose_name="IV skills"),
        ),
    ]
