# Generated by Django 4.1.6 on 2023-03-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0002_alter_medicalcareprofile_exp"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalcareprofile",
            name="hourly_rate",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
