# Generated by Django 4.1.6 on 2023-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0003_medicalcareprofile_hourly_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="exp",
            field=models.CharField(
                help_text="years of experience",
                max_length=255,
                verbose_name="experience",
            ),
        ),
    ]
