# Generated by Django 4.1.6 on 2023-02-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0003_alter_medicalcareprofile_itu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="peg_feeds",
            field=models.BooleanField(default=False, verbose_name="PEG feeds"),
        ),
    ]
