# Generated by Django 4.1.6 on 2023-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0004_alter_medicalcareprofile_peg_feeds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
