# Generated by Django 4.1.6 on 2023-02-11 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0005_alter_medicalcareprofile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalcareprofile",
            name="uid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
