# Generated by Django 4.1.6 on 2023-02-11 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0006_medicalcareprofile_uid_alter_medicalcareprofile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="uid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
