# Generated by Django 4.1.6 on 2023-02-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0007_alter_medicalcareprofile_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="a_e",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="administrating_injection",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="female_catheterisation",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="itu",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="iv_skills",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="male_catheterisation",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="nurse_practitioner",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="palliative_care",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="peg_feeds",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="phlebotomy",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="practice_nurse",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="smart_care_user",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="system_one_user",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="tracheotomy",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="vaccinations",
        ),
        migrations.RemoveField(
            model_name="medicalcareprofile",
            name="wound_care",
        ),
        migrations.AddField(
            model_name="medicalcareprofile",
            name="skills",
            field=models.ManyToManyField(
                related_name="skill_list", to="med_care.skill"
            ),
        ),
    ]
