# Generated by Django 4.1.6 on 2023-02-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0008_skill_remove_medicalcareprofile_a_e_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="qualification_list",
                to="med_care.qualification",
            ),
        ),
        migrations.AlterField(
            model_name="medicalcareprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="skill_list", to="med_care.skill"
            ),
        ),
    ]
