# Generated by Django 4.1.6 on 2023-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("F", "F"), ("M", "M")], default="F", max_length=1
            ),
        ),
    ]
