# Generated by Django 4.1.6 on 2023-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_postal_code_alter_profile_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.PositiveIntegerField(default="+1", null=True),
        ),
    ]
