# Generated by Django 4.1.6 on 2023-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.TextField(default="+1", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone1",
            field=models.TextField(blank=True),
        ),
    ]
