# Generated by Django 4.1.6 on 2023-02-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_profile_address_profile_address1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_buyer",
            field=models.BooleanField(default=False),
        ),
    ]
