# Generated by Django 4.1.6 on 2023-02-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_is_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(default=True),
        ),
    ]
