# Generated by Django 4.1.6 on 2023-02-26 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("med_care", "0002_alter_medicalcareprofile_exp"),
        ("work", "0001_initial"),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("carer", "job")},
        ),
    ]
